Phase II submission improvement
mayhemheroes/peg-markdown pull request #2
Opened 2023-01-29 04:55 UTC by rnshah9

2023-02-24 19:59 UTC, xansec requested changes
Please make the requested changes.

2023-02-24 19:59 UTC, xansec commented on mayhem/Dockerfile
> +FROM --platform=linux/amd64 ubuntu:20.04 as builder
Can we revisit the sed command here? Is there a better way to get this to build?

2023-02-26 21:22 UTC, rnshah9 commented
Still kind of a hack, but much less brittle I think.

2023-02-27 18:59 UTC, xansec approved these changes
LGTM!

2023-02-27 18:59 UTC, xansec commented on wrapper.h
> +// https://stackoverflow.com/questions/72177535/how-can-i-include-a-c-header-that-uses-a-c-keyword-as-an-identifier-in-c
I guess this works.

2023-02-27 18:59 UTC, merged